name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Unit tests (host)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run tests/
        run: make all -C tests


  firmware:
    name: Firmware build (arm-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build
        run: make all

      - name: Report size
        run: make size
